# Generated by Django 4.1.1 on 2022-10-13 23:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppWeb', '0002_blog'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='descripcion',
            new_name='password',
        ),
    ]
