# Generated by Django 4.1.1 on 2022-10-13 23:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppWeb', '0003_rename_descripcion_usuario_password'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='password',
            new_name='contra',
        ),
    ]
