# Generated by Django 4.1.1 on 2022-10-18 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppWeb', '0005_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='descipcion',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='blog',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='imagenblogs'),
        ),
    ]
