# Generated by Django 4.1.1 on 2022-10-18 23:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('AppWeb', '0006_blog_descipcion_blog_imagen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='descipcion',
        ),
        migrations.AddField(
            model_name='blog',
            name='descipcio',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
