# Generated by Django 4.1.1 on 2022-10-18 23:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppWeb', '0007_remove_blog_descipcion_blog_descipcio'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='descipcio',
            new_name='descipcion',
        ),
    ]
