# Generated by Django 4.1.1 on 2022-10-18 23:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppWeb', '0008_rename_descipcio_blog_descipcion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='descipcion',
            new_name='descripcion',
        ),
    ]
